### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [Shirakumo/lichat-protocol#2]
Building with SBCL 2.3.11.165-7fa632585 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 0185613ca7941c1bfff3a58fd5cbfa305d5517d1

*lichat-protocol* fails to build with the following error:

```
Unhandled SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR in thread #<SB-THREAD:THREAD tid=2308563 "main thread" RUNNING {10017D0003}>: Lock on package COMMON-LISP violated when defining WARNING as a class while in package LICHAT-PROTOCOL.

```

[Full log here](http://report.quicklisp.org/2024-05-09/failure-report/lichat-protocol.html)

**Comment by Shinmera** [comment]
Sorry for the release blocker!
